### PR TITLE
Fix LIBDIR location by upgrade waf to 1.9.14 and enabling use of --libdir option

### PR DESCRIPTION
**Pull request by simonvanderveldt**
Waf currently incorrectly determines the `LIBDIR` on amd64 when a `/usr/lib32` directory is present.
In that case it'll always set `LIBDIR` to `/usr/lib`. This means libmonome's 64 bit libraries will be installed into `/usr/lib`, which is not good since that's a 32bit (backwards compatibility) location.

I tried to flag it/get it fixed in waf but they kindly requested me to create a PR with new tests, which is a bit too much yak shaving for me.

Since waf has had a `--libdir` option for quiet some time to override the `LIBDIR` I think it's easier to just upgrade waf and make use of this option.
That's what this PR does. It upgrades waf to the latest 1.9.x release and enables the use of the `./waf configure --libdir` option.

I tested both configuring and building using different config options and all of them worked without issue and the libs now get installed to the correct `/usr/lib64`.

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
Hmm, not sure why travis is failing, the cython dependency seems to be purely in the `./wscript` file.

**Comment by simonvanderveldt** [comment]
Updated to waf 2.0.0 which was just releases over the weekend :)

**Comment by simonvanderveldt** [comment]
Seems like waf's `load()` function has changed and it now fails when the module(?) that's being loaded doesn't exist.
Shall I update the Travis config so it installs cython?

**Comment by tehn** [comment]
the seems like a good idea, thank you!

**Comment by simonvanderveldt** [comment]
> the seems like a good idea, thank you!

Done! :)

**Pull request merged**
